### ISSUE TITLE
Variant Ores: nuggets and Tinkers Construct smelting

### ISSUE THREAD

**Issue by Thyriel** [RoMiMoCo/Ores#14]
I'm not sure how that comes as your mod doesn't seem to add smelting in Tinkers by it's own. I tried around by removing vanilla ores and using your mods variant ores instead.
Works great so far, especially as you are registering the oreDict automatically i can use my own "Iron", "Gold", etc. in vanilla recipes.
But what's a bit strange is that Tinkers Construct is taking your smallest nugget as a vanilla nugget and the bigger nuggets are each smelting for double the amount of the previous nugget.
So when smelting in Tinkers Construct smeltery you get:
16mB smallest nugget
up to 122mB for biggest nugget (which should be half an ingot)
while ingot is 144mB

Maybe it would be better to remove the oreDict entry on your own variant nuggets that drop out of the ore and additionally add a vanilla style nugget for the generated ores that are 1/9th of an ingot to prevent problems like these ? (Would also make it possible to better integrate non vanilla custom ores from your mod with InfiniTic into TC)

edit: Just noticed too, you can't deconstruct a vanilla named custom ore ingot into the "half ingot" nuggets. The recipe is shown in JEI but it deconstructs to 9 vanilla nuggets. Although this doesn't seem to be abuseable as your smallest nuggets are useable as vanilla nuggets in recipes but they can't be used in 9 nuggets > 1 ingot recipe.

**Comment by RoMiMoCo** [comment]
Yeah, that is a strange interaction.  From my experience, none of the variant ores except the "Rich" ore will smelt in the smeltery.  I never tried with the actual ingot variants, so it's pretty cool that they do smelt, but yeah, weird how they do.  I never did any actual TiCon integration, so it is all oredict based.  For 0.3.0 I'm planning on actually doing the integration for TiCon at least as far as the smeltery smelting is concerned (I don't think I'll add any material properties).

The deconstructing of vanilla-named ores is a bug that I've noticed.  I think i'll be able to remove the vanilla recipes, however I've heard that that can cause crashes and weirdness.  I'll most likely gate the recipe removals behind a config option.

**Comment by RoMiMoCo** [comment]
fixed in 0.3.0
