### ISSUE TITLE
Load localizations at runtime without requiring a resourcepack

### ISSUE THREAD

**Issue by RoMiMoCo** [RoMiMoCo/Ores#18]
Find a way to load the localization file at runtime, without requiring it to be placed into a resourcepack.

**Comment by RoMiMoCo** [comment]
split from #17

**Comment by Thyriel** [comment]
Maybe that would be a simple solution for you:
- check if Resource Loader mod is installed and link it as dependancy on curseforge ( https://minecraft.curseforge.com/projects/resource-loader )
- if yes, create the en_us.lang file in "(root)/resources/romimoco/lang/en_us.lang"

It loads the language file automatically then and doesn't need a pack.mcmeta
