### ISSUE TITLE
Gem Cut "Trilliant" Render Issue

### ISSUE THREAD

**Issue by CatastropheBlack** [RoMiMoCo/Ores#30]
When specifying the gem cut "trilliant" in oreDefinitions.json, the game fails to render the gem, instead showing a square of the specified gem color.  Other cuts do not have this issue.

Using MC 1.12.2, Forge 14.23.2.2661, and RoMiMoCo-Ores 0.3.1

![romimocoores031trilliantcut2](https://user-images.githubusercontent.com/33291018/37980620-c2a6212a-31a8-11e8-8d56-8accbdc51ee7.png)

![romimocoores031trilliantcut](https://user-images.githubusercontent.com/33291018/37980615-bf2d6d28-31a8-11e8-9888-d74546fb59ed.png)

**Comment by RoMiMoCo** [comment]
Caused by the .png being 14x16 rather than 16x16

fixed in 0.3.2
