### ISSUE TITLE
No Armor/Tools Generated for Defined Ores without Mod Generated Gems

### ISSUE THREAD

**Issue by CatastropheBlack** [RoMiMoCo/Ores#31]
If a gem ore is added to oreDefinitions.json and specified to drop an existing gem (ie: minecraft:emerald), no armor or tools are generated.  However, tools and armor are generated if the drops are defined with type and cut and new gems are generated (romimocoores:gememerald).  Existing gems with the same name are interchangeable in armor/tool recipes created by the mod.

oreDefinitions.json:
```
{
  "OreList": [

  ],

  "GemList": [
    
    {
      "Name" : "emerald",
      "Color": "0x1fdc66",
      "Hardness":"4",
      "Harvestlevel":"2",
      "Drops":"minecraft:emerald"
    }

  ]
}
```
Expectation:
**No** ore, **no** gem, _new_ tools & armor

Result:
**No** ore, **no** gem, **no** tools & armor
![romimocoemeraldgen1](https://user-images.githubusercontent.com/33291018/38217524-f100cd4e-368b-11e8-9e7c-a3496b5639c3.png)

oreDefinitions.json:
```
{
  "OreList": [

  ],

  "GemList": [
    
    {
      "Name" : "emerald",
      "Color": "0x1fdc66",
      "Hardness":"4",
      "Harvestlevel":"2",
      "Drops":{
        "Type":"gem",
        "Cut":"round"
      }
    }

  ]
}
```
Expectation:
**No** ore, _new_ gem, _new_ tools & armor

Result:
**No** ore, _new_ gem, _new_ tools & armor
![romimocoemeraldgen2](https://user-images.githubusercontent.com/33291018/38217864-102c18c6-368d-11e8-8d3d-1bcd6b8f485f.png)

oreDefinitions.json: (copied from oreDefinitions.json.sample)
```
{
  "OreList": [

  ],

  "GemList": [
    
    {
      "Name" : "emerald",
      "Color": "0x00FF00",
      "Hardness":"4.5",
      "Harvestlevel":"3",
      "Drops":"minecraft:emerald",
      "Generation":{
        "MinY": 5,
        "MaxY": 32,
        "SpawnChance": 5,
        "VeinSize": 4,
        "Biomes": [
          "extreme_hills",
          "smaller_extreme_hills",
          "extreme_hills_with_trees",
          "mutated_extreme_hills",
          "mutated_extreme_hills_with_trees"
        ]
      }
    }

  ]
}
```
Expectation:

_New_ ore, **no** gem, _new_ tools & armor

Result:
_New_ ore, **no** gem, **no** tools & armor
![romimocoemeraldgen3](https://user-images.githubusercontent.com/33291018/38217897-29b925f4-368d-11e8-8c33-7c0eec0e0da1.png)

**Comment by RoMiMoCo** [comment]
This is fixed in 0.3.2, Situations 1 & 3 now behave as expected.  0.3.2 should be uploaded to curse this evening.
