### ISSUE TITLE
Feature Request: nether ores

### ISSUE THREAD

**Issue by serhiicherepanov** [RoMiMoCo/Ores#35]
Will be nice to have it, and ores for the End.

**Comment by RoMiMoCo** [comment]
This is actually a part of #23.  As part of prep for 1.13, I'll be flattening my blocks from using metadata to using IBlockStates for the variants.  As part of that I'll add a property for the "Base Rock" that the ore is generating in.  Until I do that, Nether and End ores aren't really feasible, as they would still use the overworld stone texture as their base.  It's on the list though.
